on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: 'Aakash'
      # Use the output from the `hello` step
      - name: Print Something
        run: echo "Testing github actions"
      
      - name: LORD murugan
        run: (ls x.txt && echo yes) || echo no
      
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      
#       - name: Check file existence
#         id: check_files
#         uses: actions/hello-world-docker-action@v1
#         with:
#           files: "README.md,package.json"

      - name: Code Inspector GitHub action
        uses: codeinspectorio/github-action@v1



